version: '3.8'
services:
  bankapi:
    build:
      context: .
      dockerfile: BankApi/Dockerfile
    image: bankapi:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=db;Port=5432;Database=bankdb;Username=postgres;Password=postgrespw
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: bankdb
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
